version: "3.9"
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    user: 1000:1000 # Add this line
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DJANGO_SECRET_KEY=django-insecure-s_&rp386x-xj*a(*_a1yo8=8#-j$$1^x8qfd*ew6t)ejgf5lao$$
      - "DJANGO_DEBUG=True"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:

